openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  /{num}:
    parameters:
      - name: num
        in: path
        required: true
        schema:
          type: integer
          format: int32
    get:
      summary: test path parameters before hello api
      operationId: helloNum
      responses:
        200:
          $ref: '#/components/responses/Success'
      x-vertx-event-bus:
        address: service.hello
        method: helloNum
  /hello:
    x-vertx-event-bus:
      address: service.hello
      timeout: 1950
    get:
      summary: hello test
      operationId: hello
      parameters:
        - $ref: '#/components/parameters/NameParam'
        - name: email
          in: query
          required: false
          schema:
            type: string
            format: email
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                allOf:
                  - $ref: '#/components/schemas/Success'
                  - type: object
                    properties:
                      msg:
                        type: string
                        minLength: 3
      x-vertx-event-bus:
        method: hello
    post:
      summary: add hello object
      operationId: add
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                properties:
                  success:
                    type: boolean
                    default: true
                  length:
                    type: integer
                    format: int32
      x-vertx-event-bus:
        method: add
components:
  responses:
    Success:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                default: true
  parameters:
    NameParam:
      name: name
      in: query
      required: true
      schema:
        type: string
        minLength: 3
  schemas:
    Success:
      properties:
        success:
          type: boolean
          default: true
