openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: http://localhost:8080/say
paths:
  /:
    get:
      summary: say something
      operationId: say
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - msg
                properties:
                  sucess:
                    type: boolean
                    default: true
                  msg:
                    type: string
      x-vertx-event-bus:
        address: service.say
        method: say
